// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1nUhtRtyO6-qo-Sfm8O63xaevJDVyG4o',
    appId: '1:64402100539:web:c4979e0a9f63e95484a71e',
    messagingSenderId: '64402100539',
    projectId: 'seesights-19c31',
    authDomain: 'seesights-19c31.firebaseapp.com',
    storageBucket: 'seesights-19c31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4OisUmB6Q3IGj_Px1a68ASvBK0B0shoI',
    appId: '1:64402100539:android:4cb4f1d5bcaf0da084a71e',
    messagingSenderId: '64402100539',
    projectId: 'seesights-19c31',
    storageBucket: 'seesights-19c31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChX3oXVlt8Q91bkCUEMJU_WQpueFcH2UM',
    appId: '1:64402100539:ios:440c05f928ea40bd84a71e',
    messagingSenderId: '64402100539',
    projectId: 'seesights-19c31',
    storageBucket: 'seesights-19c31.appspot.com',
    iosBundleId: 'com.example.seeSights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChX3oXVlt8Q91bkCUEMJU_WQpueFcH2UM',
    appId: '1:64402100539:ios:440c05f928ea40bd84a71e',
    messagingSenderId: '64402100539',
    projectId: 'seesights-19c31',
    storageBucket: 'seesights-19c31.appspot.com',
    iosBundleId: 'com.example.seeSights',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1nUhtRtyO6-qo-Sfm8O63xaevJDVyG4o',
    appId: '1:64402100539:web:0f31c73effbaf0e784a71e',
    messagingSenderId: '64402100539',
    projectId: 'seesights-19c31',
    authDomain: 'seesights-19c31.firebaseapp.com',
    storageBucket: 'seesights-19c31.appspot.com',
  );

}